/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef WIN32_COLOR_GUIDE_PRIVATE_H
#define WIN32_COLOR_GUIDE_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.0.0.0"
#define VER_MAJOR	1
#define VER_MINOR	0
#define VER_RELEASE	0
#define VER_BUILD	0
#define COMPANY_NAME	"Akshat Singh"
#define FILE_VERSION	"1.0.0.0"
#define FILE_DESCRIPTION	"Win32 Color Guide"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"Win32 Color Guide"
#define PRODUCT_VERSION	"1.0.0.0"

#endif /*WIN32_COLOR_GUIDE_PRIVATE_H*/
